#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SITE_DIR="${AREND_SITE_DIR:-$DIR/../../Site}"

git commit "$1" --amend

if [ "$?" != "0" ]; then
    exit $?
fi

MSG=`git show -s --format=%B HEAD`
cd $SITE_DIR
git add .
git reset --soft HEAD^^
git commit -m"$MSG"
