#!/bin/bash

if [ -z ${NOSYNC+x} ] && [ `git rev-parse --abbrev-ref HEAD` = "master" ]
then
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    SITE_DIR="${AREND_SITE_DIR:-$DIR/../../../Site}"

    MSG=`git show -s --format=%B HEAD`
    cd $SITE_DIR
    git add .
    git commit -m"$MSG"
fi
